
# Setup
title:        欢迎你
tagline:      这是我的主页
baseurl:      ""
paginate:     1
locale:       "zh_CN"

# About/contact
author:
  name:       名字
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

